defmodule UnifiedIUR do
  @moduledoc """
  UnifiedIUR - Intermediate UI Representation

  A pure data representation layer for user interfaces.

  UnifiedIUR provides simple, immutable data structures that represent
  UI elements without any rendering logic or platform dependencies.

  ## Core Concepts

  UnifiedIUR consists of several types of UI elements:

  * **Widgets** - Basic UI components (Text, Button, Label, TextInput, etc.)
  * **Layouts** - Container elements that arrange widgets (VBox, HBox)
  * **Style** - Visual styling attributes

  ## Usage

  UnifiedIUR structs are pure data containers that can be created
  directly or generated by a DSL:

      # Direct creation
      button = %UnifiedIUR.Widgets.Button{
        id: :submit,
        label: "Submit",
        on_click: :submit
      }

      # Via DSL (requires unified_ui package)
      defmodule MyApp.UI do
        use UnifiedUi.Dsl

        ui do
          button "Submit", on_click: :submit
        end
      end

  ## Element Protocol

  The `UnifiedIUR.Element` protocol provides a consistent interface
  for working with UI elements:

      UnifiedIUR.Element.children(widget)  # Get child elements
      UnifiedIUR.Element.metadata(widget) # Get element metadata

  This allows generic tree traversal and manipulation of UI structures.

  ## Platform Integration

  Platform libraries can consume UnifiedIUR by implementing
  converters that transform IUR structs into their native format:

      # TermUi example
      defmodule TermUi.Renderers.IUR do
        def render(%UnifiedIUR.Widgets.Button{} = button) do
          # Convert to TermUi button
        end
      end
  """

  @type element :: UnifiedIUR.Element.t()

  # Widget types
  @type text :: UnifiedIUR.Widgets.Text.t()
  @type button :: UnifiedIUR.Widgets.Button.t()
  @type label :: UnifiedIUR.Widgets.Label.t()
  @type text_input :: UnifiedIUR.Widgets.TextInput.t()
  @type gauge :: UnifiedIUR.Widgets.Gauge.t()
  @type sparkline :: UnifiedIUR.Widgets.Sparkline.t()
  @type bar_chart :: UnifiedIUR.Widgets.BarChart.t()
  @type line_chart :: UnifiedIUR.Widgets.LineChart.t()
  @type column :: UnifiedIUR.Widgets.Column.t()
  @type table :: UnifiedIUR.Widgets.Table.t()

  # Layout types
  @type vbox :: UnifiedIUR.Layouts.VBox.t()
  @type hbox :: UnifiedIUR.Layouts.HBox.t()

  # Style type
  @type style :: UnifiedIUR.Style.t()
end
